enum EventType {
  Enter,
  Exit,
},
/**
 *   An event is the start or end of a token amongst other events.
 *   Tokens can “contain” other tokens, even though they are stored in a flat
 *   list, through `enter`ing before them, and `exit`ing after them.
 */
type Event = (EventType, Token, TokenizeContext),
/**
 *   Another event is the start or end of a token amongst other events.
 *   Tokens can “contain” other tokens, even though they are stored in a flat
 *   list, through `enter`ing before them, and `exit`ing after them.
 */


enum EventType2 {
  Enter2,
  Exit2,
},
// line comment
type Event2 = (EventType2, Token, TokenizeContext)
