module Imports

include "runtime/unsafe/memory"
include "runtime/unsafe/tags"
include "list"
from List use { length, map }

include "runtime/unsafe/wasmi32"
from WasmI32 use { 
  add as (+),
  mul as (*),
  xor as (^),
  shl as (<<)
}

expose foreign wasm storage_read: (WasmI64, WasmI64, WasmI64) -> WasmI64 as storageRead from "env"


include "runtime/unsafe/wasmi32"
from WasmI32 use {
  eq, // comment1
  // comment 3
  and as (&), // comment 2
  or as (|)
  // no signed imports, as care should be taken to use signed or unsigned operators
}

expose foreign wasm promise_results_count: () -> WasmI64 as promiseResultsCount from "env"
