let div3 = DOM::query("#innerDiv") in
let makeButtonHTML =
  (lambda n:
    strcat(strcat('<div class="row pt-1 pb-1"><button type="button" class="btn btn-primary mx-auto" id="butt', toString(n)), '">Click me!</button></div>')) in
let html = ('', 0) in
let rec addButton = (lambda:
  begin
    html[0] := strcat(html[0], makeButtonHTML(html[1]));
    DOM::dangerouslySetInnerHTML(div3, html[0]);
    print("No, really.");
    let id = strcat("#butt", toString(html[1])) in
    begin
      setEventListeners(html[1]);
      html[1] := html[1] + 1;
    end
  end
),
setEventListeners = (lambda n:
  if equal(n, 0):
    DOM::addEventListener(DOM::query("#butt0"), "click", addButton)
  else:
    begin
      let elem = DOM::query(strcat("#butt", toString(n))) in
      DOM::addEventListener(elem, "click", addButton);
      setEventListeners(n - 1);
    end
) in
begin
  addButton();
  print("Click it.")
end
