// Note: This file doesn't include the Recursive type test
// because it isn't achievable with `let mut`

export enum Opt<a> { None, Some(a) }

let mut z = None
z = Some(z)

let mut y = None

assert !(z == y)

y = Some(y)
assert z == y

export record Rec {
  int: Number,
  mut r: Opt<Rec>
}

let a = { int: 5, r: None }
let b = { int: 5, r: None }

a.r = Some(a)

assert a is a
assert a == a

assert !(a == b)

b.r = Some(b)

assert !(a is b)
assert a == b

print(void)
