module RecursiveEqualBox

provide enum rec R {
  Atom,
  Recursive(Box<Option<R>>),
}

let t = box(None)
let u = box(None)
let x = Recursive(t)
let w = Recursive(u)

t := Some(x)

assert !(x == w)

u := Some(w)

assert x == w

provide record rec Rec {
  int: Number,
  r: Box<Option<Rec>>,
}

let a = { int: 5, r: box(None) }
let b = { int: 5, r: box(None) }

a.r := Some(a)

assert a is a
assert a == a

assert !(a == b)

b.r := Some(b)

assert !(a is b)
assert a == b

print("OK")
