# Contrived example to test *ADVANCED* tail calls

let rec is_even_help = (n, b) => {
  let x = (n, n, b, n);
  if (n == 0) {
    b
  } else {
    # Note the different argument size
    # (We bounce back and forth between
    #  different stack sizes with this
    #  implementation)
    is_odd(n - 1)
  }
},

is_odd_help = (n, b) => {
  let x = (n,);
  if (n == 1) {
    b
  } else {
    # See above
    is_even(n - 1)
  }
},

is_even = (n) => { is_even_help(n, true) },
is_odd = (n) => { is_odd_help(n, true) };

is_odd(9999)
