import foreign wasm fd_write: (
  WasmI32,
  WasmI32,
  WasmI32,
  WasmI32
) -> WasmI32 from "wasi_snapshot_preview1"

export let fd_write: (WasmI32, WasmI32, WasmI32, WasmI32) -> WasmI32 =
  (
    fd,
    iovs,
    iovs_len,
    nwritten,
  ) => {
  fd_write(fd, iovs, iovs_len, nwritten)
  fd_write(fd, iovs, iovs_len, nwritten)
  fd_write(fd, iovs, iovs_len, nwritten)
}

export let args_get: (WasmI32, WasmI32) -> WasmI32 = (a, b) => {
  76n
}
