module WasiPolyfill

foreign wasm fd_write: (
  WasmI32,
  WasmI32,
  WasmI32,
  WasmI32,
) -> WasmI32 from "wasi_snapshot_preview1"

expose let fd_write: (WasmI32, WasmI32, WasmI32, WasmI32) -> WasmI32 =
  (
    fd,
    iovs,
    iovs_len,
    nwritten,
  ) => {
  fd_write(fd, iovs, iovs_len, nwritten)
  fd_write(fd, iovs, iovs_len, nwritten)
  fd_write(fd, iovs, iovs_len, nwritten)
}

expose let args_get = (a, b) => {
  76n
}
