module WasiPolyfill

foreign wasm fd_write: (
  WasmI32,
  WasmI32,
  WasmI32,
  WasmI32,
) => WasmI32 from "wasi_snapshot_preview1"

provide let fd_write: (WasmI32, WasmI32, WasmI32, WasmI32) => WasmI32 =
  (
    fd,
    iovs,
    iovs_len,
    nwritten,
  ) => {
  fd_write(fd, iovs, iovs_len, nwritten)
  fd_write(fd, iovs, iovs_len, nwritten)
  fd_write(fd, iovs, iovs_len, nwritten)
}

provide let args_get = (a, b) => {
  76n
}
