(library
 (name docblock)
 (public_name graindoc.docblock)
 (modules docblock docir errors)
 (libraries
  grain
  grain_diagnostics
  grain_utils
  ppx_sexp_conv.runtime-lib
  sexplib)
 (preprocess
  (pps ppx_sexp_conv)))

(library
 (name markdown_backend)
 (public_name graindoc.markdown_backend)
 (modules markdown_backend)
 (libraries
  grain
  grain_diagnostics
  grain_utils
  grain_formatting
  graindoc.docblock))

(executable
 (name graindoc)
 (public_name graindoc)
 (package graindoc)
 (modules graindoc)
 (modes exe js)
 (flags
  (:standard
   (:include ./config/flags.sexp)))
 (libraries
  cmdliner
  grain
  grain_diagnostics
  grain_utils
  graindoc.docblock
  graindoc.markdown_backend
  binaryen
  dune-build-info))
