# This Dockerfile constructs a minimal environment in which Grain programs can be compiled.
# The environment is only meant to build Grain programs, not develop the compiler.

FROM node:16 as builder

LABEL name="Grain"
LABEL description="Grain CLI"
LABEL vcs-url="https://github.com/grain-lang/grain"
LABEL maintainer="team@grain-lang.org"

COPY . /grain

WORKDIR /grain

# Build the compiler and CLI
RUN npm ci && \
    npm run compiler build

# Remove build files
RUN rm -rf node_modules compiler/_esy

FROM node:16-slim

COPY --from=builder /grain /grain
WORKDIR /grain

# Link CLI in new image and restore only necessary node_modules
RUN NODE_ENV=production npm ci

# Set up container environment
WORKDIR /
CMD [ "/bin/bash" ]
