module Aliases

type Foo = String

type Foo = 
  String

type Foo<
a
> = String

type Foo<a,
  b> = String

type Foo1<a,
  b> = String 

type Foo2<
a, b
> = String

type AReallyReallyReallyReallyReallyReallyReallyReallyReallyLongLineBreakingType<a,
  b> = String

type Foo3<a, 
  b> = String

type Foo4<a, b> = String

type Foo5 = String

type Foo<a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,x,y,z,aa,ab,ac,ad,ae,af,ag,ah,ai> = String

type Bar<a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,x,y,z,aa,ab,ac,ad,ae,af,ag,ah,ai> = Foo<a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,x,y,z,aa,ab,ac,ad,ae,af,ag,ah,ai>

type Foo2 = 
  VeryVeryLongVeryVeryLongVeryVeryLongVeryVeryLongVeryVeryLongVeryVeryLongVeryVeryLongVeryVeryLongVeryVeryLong
