module Application2

init(position, index => {filtered[index]});

forEach(
  el =>
    if (fn(el)) {
      filtered[position] = el;
      position += 1;
    },
  array,
);

init2(position, index => {
    filtered[index]
    true
    })

init3(index => {
    filtered[index]
    true
    },positions)

[
  fn(x => {let _ = x}),
  fn(y => {
    let _ = y
    void
  }),
  fn(z => {let _ = z}),
]

[
  fn(x => {let _ = x}),
  fn(y => {
    let _ = y
    void
  }),
  fn(z => {let _ = z}),
  fn(z => {let _ = z}),
  fn(z => {let _ = z}),
  fn(z => {let _ = z}),
  fn(z => {let _ = z}),
]

let makePrettyPrintJSONWriter = String.forEachCodePoint(c => {
  // a
  void
}, "")

record Foo { mut idx: Number }; let foo = { idx: 1 }; foo.idx += 2
