module Binops

fofdfdfdfdfdfdfdfdfdfdfdo &&
  bafdfdfdfdfdfdddefdfdfdfdfdr &&
  badfdfdfdfdfdfdffdffdfdfdz

let x = fofdfdfdfdfdfdfdfdfdfdfdo &&
  bafdfdfdfdfdfdddefdfdfdfdfdr &&
  badfdfdfdfdfdfdffdffdfdfdz

if (
  fofdfdfdfdfdfdfdfdfdfdfdo &&
  bafdfdfdfdfdfdddefdfdfdfdfdr &&
  badfdfdfdfdfdfdffdffdfdfdz
)
  true

let a = (2 >> 1) << 1

let a1 = ((2 >> 1) << 1) >> 1

let x = 1 * (2 + 3)
let y = 1 * 2 + 3
let cond = false && false || false

let z = 1 + 2 + 3

let p = 1 + 2 - 3

let p2 = 1 - 2 + 3

let y = 1/2 + 3

let ya = 1 / (2 + 3)

let y1 = 1 + 2/3

let c = 1 < 2 || 2 < 3 || 3 < 4

let (>>>>>) = (>>)

let a = (2 >>>>> 1) << 1

let (+++) = (+)
let (---) = (-)

let zz = 1 +++ 2 --- 3

(5 + 5): Number
