module FunctionParams

let single_arg = (x) => x

let unit_arg = () => 3

let two_args = (x,y) => 4

provide let fake_write: (int, int, int, string) => string =
  (
    fd,
    iovs,
    iovs_len,
    nwritten,
  ) => {
  "ok"
}

let lots_of_args = (verylonglong1,verylonglong2,verylonglong3,verylonglong4,verylonglong1) => {
  print("lots of args")
}

let stringTailMatcher =  (toMatch, len) =>
  (
    buf: Number,
    pos: Number,
    start: Number,
    limit: Number,
    end: Number,
    state,
    stack,
  ) => {
    true
  }

let f: Number -> (Number, Number) -> Number = a => (b, c) => a + b + c

let namedArg: (?suffix: String) => String = (suffix="") => suffix
