module Includes

include "runtime/unsafe/memory"
include "runtime/unsafe/tags"
include "list"
include "option" as Opt
include "option" as
 Opt
include /* special include */ "array"
include "array" as  /* special include */ Foo
use List.{ length, map, forEach as each }
use Opt.{ module MutableOpt, module ImmutableOpt as Imm, type Opt, type Opt as OptAlias }
use Opt.{ module MutableOpt, /* comment1 */ module ImmutableOpt /* comment2 */ as /* comment3 */ Imm /* comment4 */, /* comment5 */ type /* comment6 */ Opt, type Opt as /* comment7 */ OptAlias, exception Exc as /* comment8 */ E, exception Exc2 /* comment9 */ }

include "runtime/unsafe/wasmi32"
use WasmI32.{ 
  add as (+),
  mul as (*),
  xor as (^),
  shl as (<<)
}

provide foreign wasm storage_read: (WasmI64, WasmI64, WasmI64) => WasmI64 as storageRead from "env"


include "runtime/unsafe/wasmi32"
use WasmI32.{
  eq, // comment1
  // comment 3
  and_ as (&), // comment 2
  or as (|)
  // no signed imports, as care should be taken to use signed or unsigned operators
}

provide foreign wasm promise_results_count: () => WasmI64 as promiseResultsCount from "env"

provide {exception MyExc as E2}
