module Includes

include "runtime/unsafe/memory"
include "runtime/unsafe/tags"
include "list"
include "option" as Opt
include "option" as Opt
include "array"
include "array" as Foo
from List use { length, map, forEach as each }
from Opt use { MutableOpt, ImmutableOpt as Imm, type Opt, type Opt as OptAlias }
from Opt use { MutableOpt, ImmutableOpt as Imm, type Opt, type Opt as OptAlias }

include "runtime/unsafe/wasmi32"
from WasmI32 use { add as (+), mul as (*), xor as (^), shl as (<<) }

provide foreign wasm storage_read: (
  WasmI64,
  WasmI64,
  WasmI64,
) -> WasmI64 as storageRead from "env"

include "runtime/unsafe/wasmi32"
from WasmI32 use { eq, and_ as (&), or as (|) }

provide foreign wasm promise_results_count: () -> WasmI64 as promiseResultsCount from "env"
