module Infix

let trimString = (str: String, end: Bool) => {
  let chars = [>] and charsLength = 0
  let mut i = 0 and offset = 1
 
  for (; i < charsLength && i > -1; i += offset) {
    let currentChar = chars[i];
    if (
      // Spacing
      currentChar != '\u{0009}'  && // Tab
      currentChar != '\u{000B}'  && // LINE TABULATION
      currentChar != '\u{000C}'  && // FORM FEED (FF)
      currentChar != '\u{0020}'  && // Space
      currentChar != '\u{00A0}'  && // No Break Space
      currentChar != '\u{FEFF}'  && // ZERO WIDTH NO-BREAK SPACE
      // Line Terminators
      currentChar != '\n' && // LF
      currentChar != '\r' // CR
    ) break
  }
  if (end) slice(0, i+1, str)
  else slice(i, charsLength, str)
}

(||+)
(||^)
(&&*&^%)
(|*)
(^^^)
(&-)
(==!)
(==$)
(==*==)
(!==^)
(<<<<<)
(<%>)
(<=>)
(>>>>)
(>>>>>>>>)
(><><><)
(+==)
(+!)
(++!)
(+-+)
(**//**)
(**)
(??)
(???)
(+.)
(-.)
(*.)
(/.)
(>>=)
(|>)
(>:)
(%%)
(===)
(!==)
(==?)
(&?)
(++)
(--)
(^*^)
(^-^)
