module ListSugar

let list = [1]

let list2 = [1,2]

let list3 = [1,2,3]

let list4 = [[1,2],[3,4],[5,6]]

let list5 = [[1,2,3],[3,4,5],[5,6,7]]


let lst = ["dsdsdshdfjkhdsjhfdsjkhfjdshjfkhsdjkfh", "dsdsdshdfjkhdsjhfdsjkhfjdshjfkhsdjkfh", "dsdsdshdfjkhdsjhfdsjkhfjdshjfkhsdjkfh", "dsdsdshdfjkhdsjhfdsjkhfjdshjfkhsdjkfh"]


let b = [1, ...list2]

let c = [4,...list2]

let fn = (x) => x
let fn2 = (x) => [x,x]

 let d = [1,2,fn(3)]

 let e = [1,...fn2(3)]

let inaBlock =  { let list3 = [1,2,3]

let list4 = [[1,2],[3,4],[5,6]]

let list5 = [[1,2,3],[3,4,5],[5,6,7]]
}

let test = [ 1, /* a */  
             2, // test 
             3, 
             ]

let test2 = [ 1, /* a */  
             2, // test 
             3, // final comment
             ]

let test3 = [ 1, // comm
            
             ]



let recs = [
    { num: 1, var:   A, str: "" },


  { num: 1, var: A, str: "foo" },  // A comment
      { num: 1, var: A, str: "bar" },
]

let t = [ 1, /*inline*/ 2, // comment
        3]

let cons = (a, b) => [a, ...b] // <-  some long comment some long comment some long comment some long comment
