module Matches

from "list" include List

record Queue<a> {
  forwards: List<a>,
  backwards: List<a>,
}

provide let push = (value, queue) => {
  match (queue) {
    { forwards: [], backwards: [] } => { forwards: [value], backwards: [] },
    // comment
    { forwards, backwards } => { forwards, backwards: [value, ...backwards] },
  }
}

provide let pop = queue => {
  match (queue) {
    { forwards: [], backwards: [] } => queue,
    { forwards: [head], backwards: [] } => { forwards: [], backwards: [] },
    { forwards: [head], backwards } =>
      { forwards: List.reverse(backwards), backwards: [] },
    { forwards: [head, ...ftail], backwards } => { forwards: ftail, backwards },
  }
}

enum Foo<a, b, c> {
  A(a, b),
  B(b, c),
}

match (A(1, 2)) {
  A(a, b) => true,
  B(b, c) => false,
}

let testFormatting = charlist => {
  match (charlist) {
    ['f', 'o', 'r', 'm', 'a', 't', ...rest] => true,
    _ => false,
  }
}
