module Variants

enum Animals {
  VeryVeryLong,
  VeryVeryLongVeryVeryLong,
  VeryVeryLongVeryVeryLongVeryVeryLong,
}

enum SmallAnimals {
  Abc,
  Def,
}

enum CabbageColor {
  Red,
  Green,
}
enum Veggie {
  Squash,
  Cabbage(CabbageColor),
  Broccoli,
}

let redCabbage = Cabbage(Red)

enum TrailingComment {
  Squash,
  Cabbage(CabbageColor),
  Broccoli,
}

enum InlineRec {
  Rec{
    x: Number,
    y: Number,
  },
  Tup(Number, Number),
}

let r = Rec{ x: 1, y: 2 }
