---
name: Enhancement or feature request.
description: Suggest an enhancement/feature request/RFC for the core Grain language.
body:
- type: textarea
  attributes:
    label: Problem description
    description: |
      A description of a problem, workflow or integration that your suggestion would solve.
      1. Make sure that you first check if your enhancement/feature request/RFC hasn't already been reported. It saves a bit of work on our end.
  validations:
    required: true
- type: textarea
  attributes:
    label: Preferred solution
    description: "A description of what changes should be made to Grain to solve the problem (If you are not sure about this, you can leave it blank)."
- type: textarea
  attributes:
    label: Alternatives
    description: "A description of any alternative solutions or enhancements considered."
- type: textarea
  attributes:
    label: Additional Information (optional)
    description: |
      If applicable, add screenshots to help demonstrate the problem or proposed solution. Code examples or related links are useful, too.