/* grainc-flags --memory-base 0x110000 */
import WasmI32 from "runtime/unsafe/wasmi32"
import Conv from "runtime/unsafe/conv"

primitive heapBase: WasmI32 = "@heap.base"
primitive heapStart: WasmI32 = "@heap.start"
primitive typeMetadata: WasmI32 = "@heap.type_metadata"

@disableGC
let doTest = () => {
  assert Conv.toInt32(heapBase) == 0x110000l
  assert Conv.toInt32(heapStart) == 0x110010l
  assert Conv.toInt32(typeMetadata) == 0x110008l
}
