/* grainc-flags --memory-base 0x110000 */
module Asserts

include "runtime/unsafe/wasmi32"

@unsafe
primitive heapBase = "@heap.base"
@unsafe
primitive heapStart = "@heap.start"
@unsafe
primitive typeMetadata = "@heap.type_metadata"

@unsafe
let doTest = () => {
  assert WasmI32.eq(heapBase, 0x110000n)
  assert WasmI32.eq(heapStart, 0x110010n)
  assert WasmI32.eq(typeMetadata, 0x110008n)
}

doTest()
