/* grainc-flags --no-gc --no-bulk-memory --no-wasm-tail-call */
module NearTest

include "runtime/unsafe/wasmi32"
include "runtime/unsafe/wasmi64"
include "./nearEnv" as Env

provide let hello = () => {
  from WasmI32 use { (+) }
  let value = "Hello, World!"
  let length = WasmI64.load32U(WasmI32.fromGrain(value), 4n)
  let ptr = WasmI64.extendI32U(WasmI32.fromGrain(value) + 8n)
  Env.valueReturn(length, ptr)
}
