/* grainc-flags --no-gc --no-bulk-memory */
module NearEnv

expose foreign wasm storage_read: (
  WasmI64,
  WasmI64,
  WasmI64,
) -> WasmI64 as storageRead from "env"
expose foreign wasm storage_write: (
  WasmI64,
  WasmI64,
  WasmI64,
  WasmI64,
  WasmI64,
) -> WasmI64 as storageWrite from "env"
expose foreign wasm storage_has_key: (
  WasmI64,
  WasmI64,
) -> WasmI64 as storageHasKey from "env"

expose foreign wasm read_register: (
  WasmI64,
  WasmI64,
) -> Void as readRegister from "env"

expose foreign wasm value_return: (
  WasmI64,
  WasmI64,
) -> Void as valueReturn from "env"
