(include_subdirs qualified)

(library
 (name grain_language_server)
 (libraries
  grain
  grain_diagnostics
  grain_parsing
  grain_utils
  uri
  grain_formatting
  ppx_deriving_yojson.runtime
  yojson
  grain_tree_sitter
  grain_tree_sitter.edit)
 (preprocess
  (pps ppx_deriving.enum ppx_deriving_yojson)))
