module BufferTest

from "array" include Array
from "string" include String
from "buffer" include Buffer
from "bytes" include Bytes
from "int32" include Int32
from "char" include Char

// it should have 0 length when buffer is created
assert Buffer.length(Buffer.make(0)) == 0
assert Buffer.length(Buffer.make(1024)) == 0

// its contents should equal other buffers with equivalent bytes
assert Buffer.toBytes(Buffer.make(0)) == Buffer.toBytes(Buffer.make(0))
let a = Buffer.make(0)
Buffer.addInt8(1s, a)
let b = Buffer.make(0)
Buffer.addInt8(1s, b)
assert Buffer.toBytes(a) == Buffer.toBytes(b)

// it should add/get int8
let byteSize = 1
let size = 8 * byteSize
let buf = Buffer.make(size)
for (let mut i = 0; i < size / byteSize; i += 1) {
  // it should add an int8
  let n = 42s
  Buffer.addInt8(n, buf)
  // it should have value n at position i
  assert Buffer.getInt8(i * byteSize, buf) == n
  // it should have length equal to i + 1
  assert Buffer.length(buf) == (i + 1) * byteSize
}

// it should add/get uint8
let byteSize = 1
let size = 8 * byteSize
let buf = Buffer.make(size)
for (let mut i = 0; i < size / byteSize; i += 1) {
  // it should add an uint8
  let n = 42us
  Buffer.addUint8(n, buf)
  // it should have value n at position i
  assert Buffer.getUint8(i * byteSize, buf) == n
  // it should have length equal to i + 1
  assert Buffer.length(buf) == (i + 1) * byteSize
}

// it should add/get int16
let byteSize = 2
let size = 8 * byteSize
let buf = Buffer.make(size)
for (let mut i = 0; i < size / byteSize; i += 1) {
  // it should add an int16
  let n = 42S
  Buffer.addInt16(n, buf)
  // it should have value n at position i
  assert Buffer.getInt16(i * byteSize, buf) == n
  // it should have length equal to i + 1
  assert Buffer.length(buf) == (i + 1) * byteSize
}

// it should add/get int16
let byteSize = 2
let size = 8 * byteSize
let buf = Buffer.make(size)
for (let mut i = 0; i < size / byteSize; i += 1) {
  // it should add an int16
  let n = 42uS
  Buffer.addUint16(n, buf)
  // it should have value n at position i
  assert Buffer.getUint16(i * byteSize, buf) == n
  // it should have length equal to i + 1
  assert Buffer.length(buf) == (i + 1) * byteSize
}

// it should add/get int32
let byteSize = 4
let size = 8 * byteSize
let buf = Buffer.make(size)
for (let mut i = 0; i < size / byteSize; i += 1) {
  // it should add an int32
  let n = 42l
  Buffer.addInt32(n, buf)
  // it should have value n at position i
  assert Buffer.getInt32(i * byteSize, buf) == n
  // it should have length equal to i + 1
  assert Buffer.length(buf) == (i + 1) * byteSize
}

// it should add/get uint32
let byteSize = 4
let size = 8 * byteSize
let buf = Buffer.make(size)
for (let mut i = 0; i < size / byteSize; i += 1) {
  // it should add an uint32
  let n = 42ul
  Buffer.addUint32(n, buf)
  // it should have value n at position i
  assert Buffer.getUint32(i * byteSize, buf) == n
  // it should have length equal to i + 1
  assert Buffer.length(buf) == (i + 1) * byteSize
}

// it should add/get float32
let byteSize = 4
let size = 8 * byteSize
let buf = Buffer.make(size)
for (let mut i = 0; i < size / byteSize; i += 1) {
  // it should add an float32
  let n = 42.0f
  Buffer.addFloat32(n, buf)
  // it should have value n at position i
  assert Buffer.getFloat32(i * byteSize, buf) == n
  // it should have length equal to i + 1
  assert Buffer.length(buf) == (i + 1) * byteSize
}

// it should add/get int64
let byteSize = 8
let size = 8 * byteSize
let buf = Buffer.make(size)
for (let mut i = 0; i < size / byteSize; i += 1) {
  // it should add an int64
  let n = 42L
  Buffer.addInt64(n, buf)
  // it should have value n at position i
  assert Buffer.getInt64(i * byteSize, buf) == n
  // it should have length equal to i + 1
  assert Buffer.length(buf) == (i + 1) * byteSize
}

// it should add/get uint64
let byteSize = 8
let size = 8 * byteSize
let buf = Buffer.make(size)
for (let mut i = 0; i < size / byteSize; i += 1) {
  // it should add an uint64
  let n = 42uL
  Buffer.addUint64(n, buf)
  // it should have value n at position i
  assert Buffer.getUint64(i * byteSize, buf) == n
  // it should have length equal to i + 1
  assert Buffer.length(buf) == (i + 1) * byteSize
}

// it should add/get float64
let byteSize = 8
let size = 8 * byteSize
let buf = Buffer.make(size)
for (let mut i = 0; i < size / byteSize; i += 1) {
  // it should add an float64
  let n = 42.0d
  Buffer.addFloat64(n, buf)
  // it should have value n at position i
  assert Buffer.getFloat64(i * byteSize, buf) == n
  // it should have length equal to i + 1
  assert Buffer.length(buf) == (i + 1) * byteSize
}

// it should clear the buffer
let buf = Buffer.make(8)
Buffer.addInt8(0s, buf)
assert Buffer.length(buf) == 1
Buffer.clear(buf)
assert Buffer.length(buf) == 0

// it should reset the buffer
let buf = Buffer.make(0)
Buffer.addInt8(0s, buf)
assert Buffer.length(buf) == 1
Buffer.reset(buf)
assert Buffer.length(buf) == 0

// it should truncate the buffer
let buf = Buffer.make(0)
Buffer.addInt8(1s, buf)
Buffer.addInt8(2s, buf)
Buffer.addInt8(3s, buf)
assert Buffer.length(buf) == 3
Buffer.truncate(1, buf)
assert Buffer.length(buf) == 1
assert Buffer.getInt8(0, buf) == 1s
let bytes = Buffer.toBytes(buf)
assert Bytes.length(bytes) == 1

// it should convert a buffer to bytes
let buf = Buffer.make(0)
Buffer.addInt8(0s, buf)
Buffer.addInt8(1s, buf)
Buffer.addInt8(2s, buf)
assert Buffer.length(buf) == 3
let bytes = Buffer.toBytes(buf)
assert Bytes.length(bytes) == 3
assert Bytes.getUint8(0, bytes) == 0us
assert Bytes.getUint8(1, bytes) == 1us
assert Bytes.getUint8(2, bytes) == 2us
assert Bytes.length(Buffer.toBytes(Buffer.make(1024))) == 0

// it should convert a buffer to a bytes slice
let buf = Buffer.make(0)
Buffer.addInt8(0s, buf)
Buffer.addInt8(1s, buf)
Buffer.addInt8(2s, buf)
assert Buffer.length(buf) == 3
let bytes = Buffer.toBytesSlice(0, 0, buf)
assert Bytes.length(bytes) == 0
let bytes = Buffer.toBytesSlice(1, 0, buf)
assert Bytes.length(bytes) == 0
let bytes = Buffer.toBytesSlice(2, 0, buf)
assert Bytes.length(bytes) == 0
let bytes = Buffer.toBytesSlice(0, 1, buf)
assert Bytes.length(bytes) == 1
assert Bytes.getUint8(0, bytes) == 0us
let bytes = Buffer.toBytesSlice(1, 1, buf)
assert Bytes.length(bytes) == 1
assert Bytes.getUint8(0, bytes) == 1us
let bytes = Buffer.toBytesSlice(2, 1, buf)
assert Bytes.length(bytes) == 1
assert Bytes.getUint8(0, bytes) == 2us
let bytes = Buffer.toBytesSlice(0, 2, buf)
assert Bytes.length(bytes) == 2
assert Bytes.getUint8(0, bytes) == 0us
assert Bytes.getUint8(1, bytes) == 1us
let bytes = Buffer.toBytesSlice(1, 2, buf)
assert Bytes.length(bytes) == 2
assert Bytes.getUint8(0, bytes) == 1us
assert Bytes.getUint8(1, bytes) == 2us
let bytes = Buffer.toBytesSlice(0, 3, buf)
assert Bytes.length(bytes) == 3
assert Bytes.getUint8(0, bytes) == 0us
assert Bytes.getUint8(1, bytes) == 1us
assert Bytes.getUint8(2, bytes) == 2us

// addBytes / toBytes
let str = "Let's get this 🍞"
let bytes = Bytes.fromString(str)
let buf = Buffer.make(0)
Buffer.addBytes(bytes, buf)
assert Buffer.toBytes(buf) == bytes

// addBytesSlice
let str = "Let's get this 🍞"
let bytes = Bytes.fromString(str)
let buf = Buffer.make(0)
Buffer.addBytesSlice(0, 0, bytes, buf)
assert Buffer.toBytes(buf) == Bytes.empty
Buffer.addBytesSlice(0, Bytes.length(bytes), bytes, buf)
assert Buffer.toBytes(buf) == bytes
let emptyBytes = Bytes.make(0)
let emptyBuffer = Buffer.make(0)
Buffer.addBytesSlice(0, 0, emptyBytes, emptyBuffer)
assert emptyBuffer == Buffer.make(0)

// addString / toString
let str = "Let's get this 🍞"
let buf = Buffer.make(0)
Buffer.addString(str, buf)
assert Buffer.toString(buf) == str

// addStringSlice
let slices = [>
  ("Let's get this 🍞", 0, 16),
  ("0123456789", -10, -1),
  ("0123456789", -1, -1),
  ("0123456789", 2, 3),
  ("0123456789", 0, 10),
  ("0123456789", 6, 6),
]
for (let mut i = 0; i < Array.length(slices); i += 1) {
  let (str, start, end) = slices[i]
  let buf = Buffer.make(0)
  Buffer.addStringSlice(start, end, str, buf)
  assert Buffer.toString(buf) == String.slice(start, end=end, str)
}

// addBytesSlice
let slices = [>
  ("Let's get this 🍞", 0, 17),
  ("0123456789", 2, 1),
  ("0123456789", 0, 10),
  ("0123456789", 6, 0),
]
for (let mut i = 0; i < Array.length(slices); i += 1) {
  let (str, off, len) = slices[i]
  let bytes = Bytes.fromString(str)
  let buf = Buffer.make(0)
  Buffer.addBytesSlice(off, len, bytes, buf)
  assert Buffer.toBytes(buf) == Bytes.slice(off, len, bytes)
}

// toStringSlice
let str = "Let's get this 🍞"
let buf = Buffer.make(0)
Buffer.addString(str, buf)
assert Buffer.toStringSlice(0, 0, buf) == ""
assert Buffer.toStringSlice(0, 1, buf) == "L"
assert Buffer.toStringSlice(6, 3, buf) == "get"
assert Buffer.toStringSlice(Bytes.length(bytes) - 4, 4, buf) == "🍞"
let a = buf
let b = Buffer.make(0)
Buffer.addString(str, b)
assert Buffer.toBytes(a) == Buffer.toBytes(b)

// addChar
let char = 'a' // 1 byte
let buf = Buffer.make(0)
Buffer.addChar(char, buf)
assert Buffer.toString(buf) == "a"
let char = '©' // 2 bytes
let buf = Buffer.make(0)
Buffer.addChar(char, buf)
assert Buffer.toString(buf) == "©"
let char = String.charAt(0, "✨") // 3 bytes
let buf = Buffer.make(0)
Buffer.addChar(char, buf)
assert Buffer.toString(buf) == "✨"
let char = '🍞' // 4 bytes
let buf = Buffer.make(0)
Buffer.addChar(char, buf)
assert Buffer.toString(buf) == "🍞"

// addCharFromCodePoint
let char = Char.code('a') // 1 byte
let buf = Buffer.make(0)
Buffer.addCharFromCodePoint(char, buf)
assert Buffer.toString(buf) == "a"
let char = Char.code('©') // 2 bytes
let buf = Buffer.make(0)
Buffer.addCharFromCodePoint(char, buf)
assert Buffer.toString(buf) == "©"
let char = Char.code('✨') // 3 bytes
let buf = Buffer.make(0)
Buffer.addCharFromCodePoint(char, buf)
assert Buffer.toString(buf) == "✨"
let char = Char.code('🍞') // 4 bytes
let buf = Buffer.make(0)
Buffer.addCharFromCodePoint(char, buf)
assert Buffer.toString(buf) == "🍞"

// addBuffer
let buf0 = Buffer.make(0)
Buffer.addString("✨", buf0)
let buf1 = Buffer.make(0)
Buffer.addString("🍩", buf1)
let buf2 = Buffer.make(0)
Buffer.addString("✨", buf2)
Buffer.addBuffer(buf1, buf0)
Buffer.addBuffer(buf2, buf0)
assert Buffer.toString(buf0) == "✨🍩✨"
let emptyBuffer = Buffer.make(0)
Buffer.addBuffer(Buffer.make(0), emptyBuffer)
assert emptyBuffer == Buffer.make(0)
// addBufferSlice
let buf0 = Buffer.make(0)
let buf1 = Buffer.make(0)
Buffer.addString("0123456789", buf1)
Buffer.addBufferSlice(1, 4, buf1, buf0)
assert Buffer.toString(buf0) == "1234"
