module Float32Test

from "float32" include Float32
use Float32.*
use Pervasives.{ (-) as numberSub }

// Constants Test
// smoke test:
assert infinity > 100000000.0f
// test infinity-specific semantics:
assert toNumber(infinity) == toNumber(infinity)
assert toNumber(infinity) == numberSub(toNumber(infinity), 1)
assert nan != nan

assert pi == 3.1415927f

assert tau == 6.2831853f

assert e == 2.7182817f
// Operations Tests
// Suppress warnings about using `fromNumber` on constants, since that's what we want to test.
let fromNumber = fromNumber
assert fromNumber(5) == 5.0f
assert fromNumber(0) == 0.0f

assert toNumber(555.0f) == 555
assert toNumber(0.0f) == 0

assert 5.0f > 4.0f
assert 5.0f >= 5.0f
assert 5.0f < 17.0f
assert 5.0f <= 5.0f
assert !(5.0f > 5.0f)
assert !(5.0f >= 22.0f)
assert !(5.0f < -17.0f)
assert !(5.0f <= 4.0f)
use Pervasives.{ (<), (>) }
assert compare(1.0f, 2.0f) < 0
assert compare(3.0f, 2.0f) > 0
assert compare(1.0f, 1.0f) == 0
assert compare(nan, nan) == 0
assert compare(1.0f, nan) > 0
assert compare(nan, 1.0f) < 0

// isNaN
assert Float32.isNaN(NaNf)
assert Float32.isNaN(1.0f) == false
assert Float32.isNaN(0.0f) == false
assert Float32.isNaN(-1.0f) == false
assert Float32.isNaN(25.76f) == false
assert Float32.isNaN(-25.00f) == false
assert Float32.isNaN(Infinityf) == false
assert Float32.isNaN(-Infinityf) == false

// isInfinite
assert Float32.isInfinite(Infinityf)
assert Float32.isInfinite(-Infinityf)
assert Float32.isInfinite(NaNf) == false
assert Float32.isInfinite(1.0f) == false
assert Float32.isInfinite(0.0f) == false
assert Float32.isInfinite(-1.0f) == false
assert Float32.isInfinite(25.76f) == false
assert Float32.isInfinite(-25.00f) == false

// min
assert Float32.min(5.0f, 5.0f) == 5.0f
assert Float32.min(5.0f, 6.0f) == 5.0f
assert Float32.min(6.0f, 5.0f) == 5.0f
assert Float32.min(0.5f, 0.25f) == 0.25f
assert Float32.min(Infinityf, 10.0f) == 10.0f
assert Float32.isNaN(Float32.min(NaNf, 10.0f))
assert Float32.isNaN(Float32.min(NaNf, Infinityf))

// max
assert Float32.max(5.0f, 5.0f) == 5.0f
assert Float32.max(6.0f, 5.0f) == 6.0f
assert Float32.max(5.0f, 6.0f) == 6.0f
assert Float32.max(0.5f, 0.25f) == 0.5f
assert Float32.max(Infinityf, 10.0f) == Infinityf
assert Float32.isNaN(Float32.max(NaNf, 10.0f))
assert Float32.isNaN(Float32.max(NaNf, Infinityf))

// abs
assert Float32.abs(-25.5f) == 25.5f
assert Float32.abs(25.5f) == 25.5f
assert Float32.isNaN(Float32.abs(NaNf))
assert Float32.abs(Infinityf) == Infinityf

// neg
assert Float32.neg(-25.5f) == 25.5f
assert Float32.neg(25.5f) == -25.5f
assert Float32.isNaN(-NaNf)
assert Float32.neg(Infinityf) == -Infinityf

// ceil
assert Float32.ceil(-25.5f) == -25.0f
assert Float32.ceil(25.5f) == 26.0f
assert Float32.ceil(25.0f) == 25.0f
assert Float32.isNaN(Float32.ceil(NaNf))
assert Float32.ceil(Infinityf) == Infinityf
// floor
assert Float32.floor(-25.5f) == -26.0f
assert Float32.floor(25.5f) == 25.0f
assert Float32.floor(25.0f) == 25.0f
assert Float32.isNaN(Float32.floor(NaNf))
assert Float32.floor(Infinityf) == Infinityf
// trunc
assert Float32.trunc(-25.5f) == -25.0f
assert Float32.trunc(25.5f) == 25.0f
assert Float32.trunc(25.0f) == 25.0f
assert Float32.isNaN(Float32.trunc(NaNf))
assert Float32.trunc(Infinityf) == Infinityf
// round
assert Float32.round(-25.5f) == -26.0f
assert Float32.round(-25.25f) == -25.0f
assert Float32.round(25.25f) == 25.0f
assert Float32.round(25.5f) == 26.0f
assert Float32.isNaN(Float32.round(NaNf))
assert Float32.round(Infinityf) == Infinityf
// sqrt
assert Float32.sqrt(25.0f) == 5.0f
assert Float32.sqrt(35.0f) == 5.916079783099616f
assert Float32.sqrt(9266609011276477657.0f) == 3044110545.180066f
assert Float32.sqrt(Infinityf) == Infinityf
assert Float32.isNaN(Float32.sqrt(NaNf))
// copySign
assert Float32.copySign(2.0f, 1.0f) == 2.0f
assert Float32.copySign(-2.0f, 1.0f) == 2.0f
assert Float32.copySign(1.0f, 2.0f) == 1.0f
assert Float32.copySign(2.0f, -1.0f) == -2.0f
assert Float32.copySign(1.0f, -2.0f) == -1.0f
assert Float32.copySign(Infinityf, 1.0f) == Infinityf
assert Float32.copySign(Infinityf, -1.0f) == -Infinityf
assert Float32.copySign(1.0f, Infinityf) == 1.0f
assert Float32.copySign(1.0f, -Infinityf) == -1.0f
assert Float32.isNaN(Float32.copySign(NaNf, 1.0f))
assert Float32.isNaN(Float32.copySign(NaNf, -1.0f))
assert Float32.copySign(1.0f, NaNf) == 1.0f
assert Float32.copySign(1.0f, -NaNf) == -1.0f
