module Float64Test

from "float64" include Float64
use Float64.*

// Constants Tests
// smoke test:
assert infinity > 100000000.0d
// test infinity-specific semantics:
use Pervasives.{ (-) as numberSub }
assert toNumber(infinity) == numberSub(toNumber(infinity), 1)
assert nan != nan

assert pi == 3.141592653589793d

assert tau == 6.283185307179586d

assert e == 2.718281828459045d
// Operation Tests
// Suppress warnings about using `fromNumber` on constants, since that's what we want to test.
let fromNumber = fromNumber
assert fromNumber(5) == 5.0d
assert fromNumber(0) == 0.0d
assert fromNumber(0.5) == 0.5d
assert fromNumber(1/2) == 0.5d
assert fromNumber(-1/2) == -0.5d
// Not exact because of ieee754 rounding error
assert fromNumber(18_446_744_073_709_551_615) == 18_446_744_073_709_552_000.0d
assert fromNumber(18_446_744_073_709_551_616) == 18_446_744_073_709_552_000.0d
assert fromNumber(18_446_744_073_709_551_616) == 18_446_744_073_709_551_616.0d
assert fromNumber(-18_446_744_073_709_551_615) == -18446744073709552000.0d
assert fromNumber(-18_446_744_073_709_551_616) == -18446744073709552000.0d
assert fromNumber(-18_446_744_073_709_551_616) == -18_446_744_073_709_551_616.0d
// overflow
assert fromNumber(1.7976931348623157e+309) == Infinityd
assert fromNumber(-1.7976931348623157e+309) == -Infinityd

assert toNumber(555.0d) == 555
assert toNumber(0.0d) == 0

// Float64.reinterpretInt64
assert Float64.reinterpretInt64(0L) == 0.0d
assert Float64.reinterpretInt64(4607182418800017408L) == 1.0d
assert Float64.reinterpretInt64(-4616189618054758400L) == -1.0d
assert Float64.reinterpretInt64(4631107791820423168L) == 42.0d
// Float64.reinterpretUint64
assert Float64.reinterpretUint64(0uL) == 0.0d
assert Float64.reinterpretUint64(4607182418800017408uL) == 1.0d
assert Float64.reinterpretUint64(13830554455654793216uL) == -1.0d
assert Float64.reinterpretUint64(4631107791820423168uL) == 42.0d

// Float64.pow tests are based on test cases from libc-test: http://nsz.repo.hu/git/?p=libc-test
/*
  libc-test is licensed under the following standard MIT license:
  Copyright © 2005-2013 libc-test AUTHORS
  Permission is hereby granted, free of charge, to any person obtaining
  a copy of this software and associated documentation files (the
  "Software"), to deal in the Software without restriction, including
  without limitation the rights to use, copy, modify, merge, publish,
  distribute, sublicense, and/or sell copies of the Software, and to
  permit persons to whom the Software is furnished to do so, subject to
  the following conditions:
  The above copyright notice and this permission notice shall be
  included in all copies or substantial portions of the Software.
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
  Portions of this software is derived from software authored by
  third parties:
  math tests use numbers under BSD and GPL licenses see src/math/ucb/*
  and src/math/crlibm/* for details
*/
// pow
assert Float64.isNaN(-8.06684839057968084d ** 4.53566256067686879d)
assert 4.34523984933830487d ** -8.88799136300345083d
  == 0.00000213471188255872853d
assert Float64.isNaN(-8.38143342755524934d ** -2.76360733737958819d)
assert Float64.isNaN(-6.53167358191348413d ** 4.56753527684274374d)
assert 9.26705696697258574d ** 4.81139208435979615d == 44909.2994151296589d
assert Float64.isNaN(-6.45004555606023633d ** 0.662071792337673881d)
assert 7.85889025304169664d ** 0.0521545267500622481d == 1.11351774134586523d
assert Float64.isNaN(-0.792054511984895959d ** 7.67640268511753998d)
assert 0.615702673197924044d ** 2.01190257903248026d == 0.376907735213801831d
assert Float64.isNaN(-0.558758682360915193d ** 0.0322398306026380407d)
assert Float64.isNaN(0.0d ** NaNd)
assert 0.0d ** Infinityd == 0.0d
assert 0.0d ** 3.0d == 0.0d
assert 0.0d ** 2.0d == 0.0d
assert 0.0d ** 1.0d == 0.0d
assert 0.0d ** 0.5d == 0.0d
assert Float64.isNaN(0.0d ** 0.0d)
assert Float64.isNaN(0.0d ** -0.0d)
assert 0.0d ** -0.5d == Infinityd
assert 0.0d ** -1.0d == Infinityd
assert 0.0d ** -Infinityd == Infinityd
assert Float64.isNaN(-0.0d ** NaNd)
assert -0.0d ** Infinityd == 0.0d
assert -0.0d ** 3.0d == -0.0d
assert -0.0d ** 0.5d == 0.0d
assert Float64.isNaN(-0.0d ** 0.0d)
assert Float64.isNaN(-0.0d ** -0.0d)
assert -0.0d ** -0.5d == Infinityd
assert -0.0d ** -1.0d == -Infinityd
assert -0.0d ** -2.0d == Infinityd
assert -0.0d ** -3.0d == -Infinityd
assert -0.0d ** -4.0d == Infinityd
assert -0.0d ** -Infinityd == Infinityd
assert Float64.isNaN(NaNd ** 0.0d)
assert Float64.isNaN(Infinityd ** 0.0d)
assert Float64.isNaN(-Infinityd ** 0.0d)
assert Float64.isNaN(1.0d ** 0.0d)
assert Float64.isNaN(-1.0d ** 0.0d)
assert Float64.isNaN(-0.5d ** 0.0d)
assert Float64.isNaN(NaNd ** -0.0d)
assert 300.0d ** 1.0d == 300.0d

assert 5.0d > 4.0d
assert 5.0d >= 5.0d
assert 5.0d < 17.0d
assert 5.0d <= 5.0d
assert !(5.0d > 5.0d)
assert !(5.0d >= 22.0d)
assert !(5.0d < -17.0d)
assert !(5.0d <= 4.0d)

// isFinite
assert Float64.isFinite(NaNd) == false
assert Float64.isFinite(Infinityd) == false
assert Float64.isFinite(-Infinityd) == false
assert Float64.isFinite(1.0d)
assert Float64.isFinite(0.0d)
assert Float64.isFinite(-1.0d)
assert Float64.isFinite(25.76d)
assert Float64.isFinite(-25.00d)

// isNaN
assert Float64.isNaN(NaNd)
assert Float64.isNaN(1.0d) == false
assert Float64.isNaN(0.0d) == false
assert Float64.isNaN(-1.0d) == false
assert Float64.isNaN(25.76d) == false
assert Float64.isNaN(-25.00d) == false
assert Float64.isNaN(Infinityd) == false
assert Float64.isNaN(-Infinityd) == false

// isInfinite
assert Float64.isInfinite(Infinityd)
assert Float64.isInfinite(-Infinityd)
assert Float64.isInfinite(NaNd) == false
assert Float64.isInfinite(1.0d) == false
assert Float64.isInfinite(0.0d) == false
assert Float64.isInfinite(-1.0d) == false
assert Float64.isInfinite(25.76d) == false
assert Float64.isInfinite(-25.00d) == false

// min
assert Float64.min(5.0d, 5.0d) == 5.0d
assert Float64.min(5.0d, 6.0d) == 5.0d
assert Float64.min(6.0d, 5.0d) == 5.0d
assert Float64.min(0.5d, 0.25d) == 0.25d
assert Float64.min(Infinityd, 10.0d) == 10.0d
assert Float64.isNaN(Float64.min(NaNd, 10.0d))
assert Float64.isNaN(Float64.min(NaNd, Infinityd))

// max
assert Float64.max(5.0d, 5.0d) == 5.0d
assert Float64.max(6.0d, 5.0d) == 6.0d
assert Float64.max(5.0d, 6.0d) == 6.0d
assert Float64.max(0.5d, 0.2d) == 0.5d
assert Float64.max(Infinityd, 10.0d) == Infinityd
assert Float64.isNaN(Float64.max(NaNd, 10.0d))
assert Float64.isNaN(Float64.max(NaNd, Infinityd))

// abs
assert Float64.abs(-25.5d) == 25.5d
assert Float64.abs(25.5d) == 25.5d
assert Float64.isNaN(Float64.abs(NaNd))
assert Float64.abs(Infinityd) == Infinityd

// neg
assert Float64.neg(-25.5d) == 25.5d
assert Float64.neg(25.5d) == -25.5d
assert Float64.isNaN(-NaNd)
assert Float64.neg(Infinityd) == -Infinityd

// ceil
assert Float64.ceil(-25.5d) == -25.0d
assert Float64.ceil(25.5d) == 26.0d
assert Float64.ceil(25.0d) == 25.0d
assert Float64.isNaN(Float64.ceil(NaNd))
assert Float64.ceil(Infinityd) == Infinityd
// floor
assert Float64.floor(-25.5d) == -26.0d
assert Float64.floor(25.5d) == 25.0d
assert Float64.floor(25.0d) == 25.0d
assert Float64.isNaN(Float64.floor(NaNd))
assert Float64.floor(Infinityd) == Infinityd
// trunc
assert Float64.trunc(-25.5d) == -25.0d
assert Float64.trunc(25.5d) == 25.0d
assert Float64.trunc(25.0d) == 25.0d
assert Float64.isNaN(Float64.trunc(NaNd))
assert Float64.trunc(Infinityd) == Infinityd
// round
assert Float64.round(-25.5d) == -26.0d
assert Float64.round(-25.25d) == -25.0d
assert Float64.round(25.25d) == 25.0d
assert Float64.round(25.5d) == 26.0d
assert Float64.isNaN(Float64.round(NaNd))
assert Float64.round(Infinityd) == Infinityd
// sqrt
assert Float64.sqrt(25.0d) == 5.0d
assert Float64.sqrt(35.0d) == 5.916079783099616d
assert Float64.sqrt(9266609011276477657.0d) == 3044110545.180066d
assert Float64.sqrt(Infinityd) == Infinityd
assert Float64.isNaN(Float64.sqrt(NaNd))
// copySign
assert Float64.copySign(2.0d, 1.0d) == 2.0d
assert Float64.copySign(-2.0d, 1.0d) == 2.0d
assert Float64.copySign(1.0d, 2.0d) == 1.0d
assert Float64.copySign(2.0d, -1.0d) == -2.0d
assert Float64.copySign(1.0d, -2.0d) == -1.0d
assert Float64.copySign(Infinityd, 1.0d) == Infinityd
assert Float64.copySign(Infinityd, -1.0d) == -Infinityd
assert Float64.copySign(1.0d, Infinityd) == 1.0d
assert Float64.copySign(1.0d, -Infinityd) == -1.0d
assert Float64.isNaN(Float64.copySign(NaNd, 1.0d))
assert Float64.isNaN(Float64.copySign(NaNd, -1.0d))
assert Float64.copySign(1.0d, NaNd) == 1.0d
assert Float64.copySign(1.0d, -NaNd) == -1.0d

// Float64.isClose
assert Float64.isClose(1.0d, 1.0d)
assert Float64.isClose(
  1.0d,
  1.0d,
  relativeTolerance=0.5d,
  absoluteTolerance=0.5d
)
assert Float64.isClose(
  1.0d,
  1.0d,
  relativeTolerance=0.0d,
  absoluteTolerance=0.0d
)
assert Float64.isClose(0.0d, 0.0d)
assert Float64.isClose(
  0.0d,
  0.0d,
  relativeTolerance=0.5d,
  absoluteTolerance=0.5d
)
assert Float64.isClose(
  0.0d,
  0.0d,
  relativeTolerance=0.0d,
  absoluteTolerance=0.0d
)
assert Float64.isClose(0.0d, 0.1d) == false
assert Float64.isClose(0.0d, 0.000000001d) == false
assert Float64.isClose(0.0d, 0.00000001d, absoluteTolerance=1e-9d) == false
assert Float64.isClose(0.0d, 0.000000001d, absoluteTolerance=1e-9d)
assert Float64.isClose(-0.0d, 0.000000001d) == false
assert Float64.isClose(-0.0d, 0.00000001d, absoluteTolerance=1e-9d) == false
assert Float64.isClose(-0.0d, 0.000000001d, absoluteTolerance=1e-9d)
assert Float64.isClose(1.1d, 1.10000001d, absoluteTolerance=1e-9d) == false
assert Float64.isClose(1.1d, 1.100000001d, absoluteTolerance=1e-9d)
assert Float64.isClose(Infinityd, Infinityd)
assert Float64.isClose(-Infinityd, -Infinityd)
assert Float64.isClose(Infinityd, -Infinityd) == false
assert Float64.isClose(NaNd, NaNd) == false

// Float64.sin - 0 to pi/2
assert Float64.sin(0.0d) == 0.0d
assert Float64.isClose(Float64.sin(Float64.pi / 6.0d), 0.5d)
assert Float64.isClose(
  Float64.sin(Float64.pi / 4.0d),
  Float64.sqrt(2.0d) / 2.0d
)
assert Float64.isClose(
  Float64.sin(Float64.pi / 3.0d),
  Float64.sqrt(3.0d) / 2.0d
)
assert Float64.isClose(Float64.sin(Float64.pi / 2.0d), 1.0d)
// Float64.sin - pi/2 to 2pi
assert Float64.isClose(
  Float64.sin(2.0d * Float64.pi / 3.0d),
  Float64.sqrt(3.0d) / 2.0d
)
assert Float64.isClose(
  Float64.sin(3.0d * Float64.pi / 4.0d),
  Float64.sqrt(2.0d) / 2.0d
)
assert Float64.isClose(Float64.sin(5.0d * Float64.pi / 6.0d), 0.5d)
// Note: This has an absolute error of 1e-15 because `Float64.pi` is not exact
assert Float64.isClose(Float64.sin(Float64.pi), 0.0d, absoluteTolerance=1e-15d)
// Float64.sin - 2pi to 3pi/2
assert Float64.isClose(Float64.sin(7.0d * Float64.pi / 6.0d), -0.5d)
assert Float64.isClose(
  Float64.sin(5.0d * Float64.pi / 4.0d),
  Float64.sqrt(2.0d) / -2.0d
)
assert Float64.isClose(
  Float64.sin(4.0d * Float64.pi / 3.0d),
  Float64.sqrt(3.0d) / -2.0d
)
assert Float64.isClose(Float64.sin(3.0d * Float64.pi / 2.0d), -1.0d)
// Float64.sin - 3pi/2 to 0
assert Float64.isClose(
  Float64.sin(5.0d * Float64.pi / 3.0d),
  Float64.sqrt(3.0d) / -2.0d
)
assert Float64.isClose(
  Float64.sin(7.0d * Float64.pi / 4.0d),
  Float64.sqrt(2.0d) / -2.0d
)
assert Float64.isClose(Float64.sin(11.0d * Float64.pi / 6.0d), -0.5d)
// Note: This has an absolute error of 1e-15 because `Float64.pi` is not exact
assert Float64.isClose(
  Float64.sin(2.0d * Float64.pi),
  0.0d,
  absoluteTolerance=1e-15d
)
// Float64.sin - special cases
assert Float64.sin(0.5d) == Float64.sin(0.5d)
assert Float64.sin(0.25d) == Float64.sin(0.25d)
assert Float64.isClose( // Note: We lose a lot of precision here do to ieee754 representation
  Float64.sin(1.7976931348623157e+308d),
  0.0049619d,
  absoluteTolerance=1e7d
) // Max F64
assert Float64.isClose(
  Float64.sin(-1.7976931348623157e+308d),
  0.00496d,
  absoluteTolerance=1e7d
) // Min F64
assert Float64.isNaN(Float64.sin(Infinityd))
assert Float64.isNaN(Float64.sin(-Infinityd))
assert Float64.isNaN(Float64.sin(NaNd))

// Float64.cos - 0 to pi/2
assert Float64.cos(0.0d) == 1.0d
assert Float64.isClose(
  Float64.cos(Float64.pi / 6.0d),
  Float64.sqrt(3.0d) / 2.0d
)
assert Float64.isClose(
  Float64.cos(Float64.pi / 4.0d),
  Float64.sqrt(2.0d) / 2.0d
)
assert Float64.isClose(Float64.cos(Float64.pi / 3.0d), 0.5d)
// Note: This has an absolute error of 1e-15 because `Float64.pi` is not exact
assert Float64.isClose(
  Float64.cos(Float64.pi / 2.0d),
  0.0d,
  absoluteTolerance=1e-15d
)
// Float64.cos - pi/2 to 2pi
assert Float64.isClose(Float64.cos(2.0d * Float64.pi / 3.0d), -0.5d)
assert Float64.isClose(
  Float64.cos(3.0d * Float64.pi / 4.0d),
  Float64.sqrt(2.0d) / -2.0d
)
assert Float64.isClose(
  Float64.cos(5.0d * Float64.pi / 6.0d),
  Float64.sqrt(3.0d) / -2.0d
)
assert Float64.isClose(Float64.cos(Float64.pi), -1.0d)
// Float64.cos - 2pi to 3pi/2
assert Float64.isClose(
  Float64.cos(7.0d * Float64.pi / 6.0d),
  Float64.sqrt(3.0d) / -2.0d
)
assert Float64.isClose(
  Float64.cos(5.0d * Float64.pi / 4.0d),
  Float64.sqrt(2.0d) / -2.0d
)
assert Float64.isClose(Float64.cos(4.0d * Float64.pi / 3.0d), -0.5d)
// Note: This has an absolute error of 1e-15 because `Float64.pi` is not exact
assert Float64.isClose(
  Float64.cos(3.0d * Float64.pi / 2.0d),
  0.0d,
  absoluteTolerance=1e-15d
)
// Float64.cos - 3pi/2 to 0
assert Float64.isClose(Float64.cos(5.0d * Float64.pi / 3.0d), 0.5d)
assert Float64.isClose(
  Float64.cos(7.0d * Float64.pi / 4.0d),
  Float64.sqrt(2.0d) / 2.0d
)
assert Float64.isClose(
  Float64.cos(11.0d * Float64.pi / 6.0d),
  Float64.sqrt(3.0d) / 2.0d
)
assert Float64.isClose(Float64.cos(2.0d * Float64.pi), 1.0d)
// Float64.cos - special cases
assert Float64.cos(0.5d) == Float64.cos(0.5d)
assert Float64.cos(0.25d) == Float64.cos(0.25d)
assert Float64.isNaN(Float64.cos(Infinityd))
assert Float64.isNaN(Float64.cos(-Infinityd))
assert Float64.isNaN(Float64.cos(NaNd))

// Float64.tan - base cases
assert Float64.tan(0.0d) == 0.0d
assert Float64.isClose(
  Float64.tan(Float64.pi / 6.0d),
  1.0d / Float64.sqrt(3.0d)
)
assert Float64.isClose(Float64.tan(Float64.pi / 4.0d), 1.0d)
assert Float64.isClose(Float64.tan(Float64.pi / 3.0d), Float64.sqrt(3.0d))
// Note: one might expect this to produce infinity but instead we produce 16331239353195370 because pi can not be represented accurately in iee754, This logic follows c
assert Float64.isClose(Float64.tan(Float64.pi / 2.0d), 16331239353195370.0d)
// Float64.tan - special cases
assert Float64.tan(0.5d) == Float64.tan(0.5d)
assert Float64.tan(0.25d) == Float64.tan(0.25d)
assert Float64.isClose( // Note: We lose a lot of precision here do to ieee754 representation
  Float64.tan(1.7976931348623157e+308d),
  -0.00496201587d,
  absoluteTolerance=1e7d
) // Max F64
assert Float64.isClose(
  Float64.tan(-1.7976931348623157e+308d),
  -0.00496201587d,
  absoluteTolerance=1e7d
) // Max F64
assert Float64.isNaN(Float64.tan(Infinityd))
assert Float64.isNaN(Float64.tan(-Infinityd))
assert Float64.isNaN(Float64.tan(NaNd))
