module Float32Test

include "float32"
from Float32 use *
from Pervasives use { (-) as numberSub }

// Constants Test
// smoke test:
assert infinity > 100000000.0f
// test infinity-specific semantics:
assert toNumber(infinity) == toNumber(infinity)
assert toNumber(infinity) == numberSub(toNumber(infinity), 1)
assert nan != nan

assert pi == 3.1415927f

assert tau == 6.2831853f

assert e == 2.7182817f
// Operations Tests
// Suppress warnings about using `fromNumber` on constants, since that's what we want to test.
let fromNumber = fromNumber
assert fromNumber(5) == 5.0f
assert fromNumber(0) == 0.0f

assert toNumber(555.0f) == 555
assert toNumber(0.0f) == 0

assert 5.0f > 4.0f
assert 5.0f >= 5.0f
assert 5.0f < 17.0f
assert 5.0f <= 5.0f
assert !(5.0f > 5.0f)
assert !(5.0f >= 22.0f)
assert !(5.0f < -17.0f)
assert !(5.0f <= 4.0f)
from Pervasives use { (<), (>) }
assert compare(1.0f, 2.0f) < 0
assert compare(3.0f, 2.0f) > 0
assert compare(1.0f, 1.0f) == 0
assert compare(nan, nan) == 0
assert compare(1.0f, nan) > 0
assert compare(nan, 1.0f) < 0
