import * from 'int32'

assert fromNumber(5) == 5l
assert fromNumber(0) == 0l

assert toNumber(555l) == 555
assert toNumber(0l) == 0

assert lnot(0xffffffffl) == 0l
assert lnot(0l) == 0xffffffffl
assert lnot(0xf0f0f0f0l) == 0x0f0f0f0fl

assert land(0b1010l, 0b10l) == 0b10l
assert land(0b1010l, 0l) == 0l

assert lor(0b1010l, 0b0101l) == 0b1111l
assert lor(0b1010l, 0l) == 0b1010l

assert lxor(0b1010l, 0b1101l) == 0b0111l
assert lxor(0b1010l, 0l) == 0b1010l

assert lsl(-1l, 1) == -2l
assert lsl(-1l, 2) == -4l
assert lsl(-1l, 3) == -8l
assert lsl(-2l, 63) == 0l
assert lsl(24l, 1) == 48l

assert lsr(4l, 1) == 2l
assert lsr(4l, 2) == 1l
assert lsr(4l, 3) == 0l
assert lsr(-1l, 63) == 1l

assert asr(-1l, 63) == -1l
assert asr(-24l, 1) == -12l

assert gt(5l, 4l)
assert gte(5l, 5l)
assert lt(5l, 17l)
assert lte(5l, 5l)
assert !gt(5l, 5l)
assert !gte(5l, 22l)
assert !lt(5l, -17l)
assert !lte(5l, 4l)
