module PriorityQueueTest

from "priorityqueue" include PriorityQueue
from "list" include List
from "array" include Array

// formatter-ignore
let lotsOfVals = [>
  3, 2, 1, 5, 3, 2, 2, 10, 6, 5,
  6, 4, 9, 10, 10, 5, 9, 6, 1, 3,
  3, 6, 6, 1, 3, 9, 6, 7, 4, 6,
  5, 4, 4, 8, 6, 4, 1, 2, 3, 8,
  8, 8, 10, 9, 6, 8, 4, 1, 1, 2,
  10, 2, 8, 10, 8, 7, 4, 8, 10, 1,
  3, 10, 4, 1, 6, 9, 6, 7, 8, 7,
  10, 4, 5, 10, 3, 2, 4, 5, 9, 5,
  3, 5, 10, 8, 7, 1, 6, 1, 4, 8,
  3, 5, 7, 2, 4, 2, 4, 5, 10, 6,
  7, 7, 7, 1, 10, 4, 9, 9, 10, 10,
  2, 5, 2, 4, 3, 10, 9, 8, 3, 5,
  7, 10, 9, 7, 8, 9, 3, 7, 7, 1,
  7, 7, 6, 3, 3, 5, 1, 8, 9, 10,
  7, 5, 9, 2, 9, 1, 6, 3, 10, 6,
  10, 2, 6, 2, 9, 3, 3, 2, 4, 1,
  9, 4, 9, 2, 9, 4, 8, 5, 6, 7,
  4, 6, 5, 4, 3, 4, 2, 9, 10, 1,
  10, 4, 4, 6, 3, 1, 9, 10, 2, 2,
  5, 5, 3, 4, 5, 8, 3, 8, 4, 10
]
let numVals = Array.length(lotsOfVals)

let sortedVals = Array.copy(lotsOfVals)
Array.sort(sortedVals)

let mut pq = PriorityQueue.make()
let mut maxPq = PriorityQueue.make(compare=(a, b) => b - a)

assert PriorityQueue.size(pq) == 0
assert PriorityQueue.isEmpty(pq)
assert PriorityQueue.peek(pq) == None
assert PriorityQueue.drain(pq) == []

assert PriorityQueue.pop(pq) == None
assert PriorityQueue.size(pq) == 0

for (let mut i = 0; i < numVals; i += 1) {
  PriorityQueue.push(lotsOfVals[i], pq)
  PriorityQueue.push(lotsOfVals[i], maxPq)
  assert PriorityQueue.size(pq) == i + 1
  assert PriorityQueue.size(maxPq) == i + 1
}

assert PriorityQueue.size(pq) == numVals
assert PriorityQueue.size(maxPq) == numVals

for (let mut i = 0; i < numVals; i += 1) {
  let val = PriorityQueue.peek(pq)
  assert val == Some(sortedVals[i])
  let maxVal = PriorityQueue.peek(maxPq)
  assert maxVal == Some(sortedVals[numVals - i - 1])

  let val = PriorityQueue.pop(pq)
  assert val == Some(sortedVals[i])
  let maxVal = PriorityQueue.pop(maxPq)
  assert maxVal == Some(sortedVals[numVals - i - 1])

  assert PriorityQueue.size(pq) == numVals - i - 1
  assert PriorityQueue.size(maxPq) == numVals - i - 1
}

assert PriorityQueue.size(pq) == 0
assert PriorityQueue.peek(pq) == None

let sortedList = Array.toList(sortedVals)
assert PriorityQueue.drain(PriorityQueue.fromList(Array.toList(lotsOfVals))) ==
  sortedList
assert PriorityQueue.drain(
  PriorityQueue.fromList(Array.toList(lotsOfVals), compare=(a, b) => b - a)
) ==
  List.reverse(sortedList)

assert PriorityQueue.fromList(Array.toList(lotsOfVals), compare=compare) ==
  PriorityQueue.fromArray(lotsOfVals)

module Immutable {
  use PriorityQueue.{ module Immutable as PriorityQueue }

  // formatter-ignore
  let lotsOfVals = [>
    3, 2, 1, 5, 3, 2, 2, 10, 6, 5,
    6, 4, 9, 10, 10, 5, 9, 6, 1, 3,
    3, 6, 6, 1, 3, 9, 6, 7, 4, 6,
    5, 4, 4, 8, 6, 4, 1, 2, 3, 8,
    8, 8, 10, 9, 6, 8, 4, 1, 1, 2,
    10, 2, 8, 10, 8, 7, 4, 8, 10, 1,
    3, 10, 4, 1, 6, 9, 6, 7, 8, 7,
    10, 4, 5, 10, 3, 2, 4, 5, 9, 5,
    3, 5, 10, 8, 7, 1, 6, 1, 4, 8,
    3, 5, 7, 2, 4, 2, 4, 5, 10, 6,
    7, 7, 7, 1, 10, 4, 9, 9, 10, 10,
    2, 5, 2, 4, 3, 10, 9, 8, 3, 5,
    7, 10, 9, 7, 8, 9, 3, 7, 7, 1,
    7, 7, 6, 3, 3, 5, 1, 8, 9, 10,
    7, 5, 9, 2, 9, 1, 6, 3, 10, 6,
    10, 2, 6, 2, 9, 3, 3, 2, 4, 1,
    9, 4, 9, 2, 9, 4, 8, 5, 6, 7,
    4, 6, 5, 4, 3, 4, 2, 9, 10, 1,
    10, 4, 4, 6, 3, 1, 9, 10, 2, 2,
    5, 5, 3, 4, 5, 8, 3, 8, 4, 10
  ]
  let numVals = Array.length(lotsOfVals)

  let sortedVals = Array.copy(lotsOfVals)
  Array.sort(sortedVals)

  let mut pq = PriorityQueue.make()
  let mut maxPq = PriorityQueue.make(compare=(a, b) => b - a)

  assert PriorityQueue.size(pq) == 0
  assert PriorityQueue.isEmpty(pq)
  assert PriorityQueue.peek(pq) == None
  assert PriorityQueue.drain(pq) == []

  pq = PriorityQueue.pop(pq)
  assert PriorityQueue.size(pq) == 0

  for (let mut i = 0; i < numVals; i += 1) {
    let newPq = PriorityQueue.push(lotsOfVals[i], pq)
    let newMaxPq = PriorityQueue.push(lotsOfVals[i], maxPq)
    assert PriorityQueue.size(pq) == i
    assert PriorityQueue.size(maxPq) == i
    assert PriorityQueue.size(newPq) == i + 1
    assert PriorityQueue.size(newMaxPq) == i + 1
    pq = newPq
    maxPq = newMaxPq
  }

  let pqWithAll = pq
  let maxPqWithAll = maxPq

  for (let mut i = 0; i < numVals; i += 1) {
    let val = PriorityQueue.peek(pq)
    assert val == Some(sortedVals[i])
    let maxVal = PriorityQueue.peek(maxPq)
    assert maxVal == Some(sortedVals[numVals - i - 1])

    let newPq = PriorityQueue.pop(pq)
    let newMaxPq = PriorityQueue.pop(maxPq)
    let expectedSize = numVals - i
    assert PriorityQueue.size(pq) == expectedSize
    assert PriorityQueue.size(maxPq) == expectedSize
    assert PriorityQueue.size(newPq) == expectedSize - 1
    assert PriorityQueue.size(newMaxPq) == expectedSize - 1
    pq = newPq
    maxPq = newMaxPq
  }

  assert PriorityQueue.size(pq) == 0
  assert PriorityQueue.size(pqWithAll) == numVals
  assert !PriorityQueue.isEmpty(pqWithAll)
  assert PriorityQueue.peek(pq) == None

  let sortedList = Array.toList(sortedVals)
  assert PriorityQueue.drain(pqWithAll) == sortedList
  assert PriorityQueue.drain(maxPqWithAll) == List.reverse(sortedList)
  assert PriorityQueue.drain(PriorityQueue.fromList(Array.toList(lotsOfVals))) ==
    sortedList
  assert PriorityQueue.drain(
    PriorityQueue.fromList(Array.toList(lotsOfVals), compare=(a, b) => b - a)
  ) ==
    List.reverse(sortedList)

  assert PriorityQueue.fromList(Array.toList(lotsOfVals), compare=compare) ==
    PriorityQueue.fromArray(lotsOfVals)
}
