import Queue from "queue"

let empty = Queue.make()
// 1 <- 2 <- 3
let sampleQueue = Queue.push(3, Queue.push(2, Queue.push(1, empty)))

// Queue.isEmpty

assert Queue.isEmpty(empty)
assert !Queue.isEmpty(sampleQueue)

// Queue.peek

assert Queue.peek(empty) == None
assert Queue.peek(sampleQueue) == Some(1)

// Queue.push

assert Queue.peek(Queue.push(1, empty)) == Some(1)
assert Queue.peek(Queue.push(4, sampleQueue)) == Some(1)

// Queue.pop

assert Queue.isEmpty(Queue.pop(empty))
assert Queue.isEmpty(Queue.pop(Queue.push(1, empty)))
assert Queue.isEmpty(Queue.pop(Queue.pop(Queue.pop(sampleQueue))))
assert Queue.peek(Queue.pop(sampleQueue)) == Some(2)
assert Queue.peek(Queue.pop(Queue.push(4, Queue.pop(sampleQueue)))) == Some(3)
