import Queue from 'queue'

let empty = Queue.make()
// 1 <- 2 <- 3
let sampleQueue = Queue.enqueue(3, Queue.enqueue(2, Queue.enqueue(1, empty)))

// Queue.isEmpty

assert Queue.isEmpty(empty)
assert !Queue.isEmpty(sampleQueue)

// Queue.head

assert Queue.head(empty) == None
assert Queue.head(sampleQueue) == Some(1)

// Queue.enqueue

assert Queue.head(Queue.enqueue(1, empty)) == Some(1)
assert Queue.head(Queue.enqueue(4, sampleQueue)) == Some(1)

// Queue.dequeue

assert Queue.isEmpty(Queue.dequeue(empty))
assert Queue.isEmpty(Queue.dequeue(Queue.enqueue(1, empty)))
assert Queue.isEmpty(Queue.dequeue(Queue.dequeue(Queue.dequeue(sampleQueue))))
assert Queue.head(Queue.dequeue(sampleQueue)) == Some(2)
assert Queue.head(Queue.dequeue(Queue.enqueue(4, Queue.dequeue(sampleQueue)))) == Some(3)
