module RationalTest

let (===) = (==)
let (!==) = (!=)

include "rational"
from Rational use *

assert fromNumber(1/2) == 1/2r
assert fromNumber(0) == 0/1r
assert fromNumber(1/1) == 1/1r
assert fromNumber(-1) == -1/1r

assert toNumber(1/2r) === 1/2
assert toNumber(0/1r) === 0
assert toNumber(1/1r) === 1
assert toNumber(-1/2r) === -1/2
assert toNumber(1/-2r) === -1/2

assert 1/2r === 1/2r
assert 1/2r === 2/4r
assert 1/1r === 2/2r
assert 1/2r != 3/4r
assert -1/2r === 1/-2r

assert 1/2r == 1/2r
assert 1/2r == 2/4r
assert 1/1r == 2/2r
assert 1/2r != 3/4r
assert -1/2r == 1/-2r

assert 1/8r + 3/8r == 1/2r
assert 1/4r + 1/2r == 3/4r
assert 1/2r + 1/2r == 1/1r

assert 1/4r - 1/4r == 0/1r
assert 3/4r - 1/4r == 1/2r

assert 1/2r * 1/2r == 1/4r
assert 1/2r * 2/1r == 1/1r
assert 3/1r * 4/1r == 12/1r

assert 1/2r / 1/2r == 1/1r
assert 1/4r / 1/2r == 1/2r

assert 1/2r > 1/3r
assert 1/2r >= 1/3r
assert 1/2r >= 1/2r
assert 1/3r < 1/2r
assert 1/3r <= 1/2r
assert 1/2r <= 1/2r

match (1/2r) {
  1/3r => fail "Impossible: 1/2r matched against 1/3r",
  1/2r => void,
  _ => fail "Impossible: 1/2r not matched against 1/2r",
}
