module RandomTest

from "wasi/random" include Random

// Just smoke tests, there's a miniscule chance these could fail

let r1 = Random.randomUint32()
let r2 = Random.randomUint32()
match ((r1, r2)) {
  (Ok(x), Ok(y)) => assert x != y,
  (Err(err), _) => throw err,
  (_, Err(err)) => throw err,
}

let r1 = Random.randomUint64()
let r2 = Random.randomUint64()

match ((r1, r2)) {
  (Ok(x), Ok(y)) => assert x != y,
  (Err(err), _) => throw err,
  (_, Err(err)) => throw err,
}

let r1 = Random.random()
let r2 = Random.random()

match ((r1, r2)) {
  (Ok(x), Ok(y)) => assert x != y,
  (Err(err), _) => throw err,
  (_, Err(err)) => throw err,
}
