let g = 7, // g represents the precision desired, p is the values of p[i] to plug into Lanczos' formula
  p = 8, // another comment
  q = 32

let myFunction2 = x => {
  let inter = x + 1
  "some string"
},
myFunction3 = y => {
  let myVal = 5
  "some string"
}

let g = 7, p = 8, q = 32

let myFunction2 = x => {
  let inter = x + 1
  "some string"
}, // a comment
myFunction3 = y => {
  let myVal = 5
  "some string"
}
