module Parens

let x = y => y + 0

x(3) + 4

let a = true
let b = false
let c = false

if (a && b || c) {
  print("who knows")
}

if (a && (b || c)) {
  print("who knows")
}

3 + 4 * 5

(3 + 4) * 5

3 - 4 + 5
3 - (4 + 5)

"a" ++ "b" ++ "c"

let zz = 3 - 4 + (5 - 6)
let zz2 = (3 - 4) * (5 - 6)
let zz3 = 3 * 4 * (5 - 6)

print(x(3) + x(4))
print(x(3) - x(4) + x(5))
print(x(3) - (x(4) + x(5)))
print(x(3) - x(4) + x(5))
