let div1 = DOM::query("#div1") in
let div2 = DOM::query("#div2") in
let div3 = DOM::query("#innerDiv") in
  if equal(div1, false) || equal(div2, false) || equal(div3, false):
    print("An element was not found!")
  else:
    begin
      DOM::setText(div1, "I'm just a div.");
      DOM::setText(div2, "Sitting here on wasm hill.");
      DOM::dangerouslySetInnerHTML(div3, "<i><pre>[[grain]]</pre></i>");
    end
