name: Binaries WIP
on:
  release:
    types: [created]

jobs:
  build-pkg-macos:
    name: Build Packaged Grain (MacOS)
    runs-on: macos-latest
    steps:
      # Many of these steps are the same as building the compiler for tests
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'
          check-latest: true

      - name: Setup environment
        run: |
          yarn config set prefix $(npm config get prefix)
          yarn global add shx

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up runtime and CLI
        run: |
          yarn

      - name: Esy setup
        run: |
          yarn compiler prepare

      - name: Esy cache
        id: esy-cache
        uses: actions/cache@v2
        with:
          path: compiler/_export
          key:  ${{ runner.os }}-esy-${{ hashFiles('compiler/esy.lock/index.json') }}

      - name: Import esy cache
        if: steps.esy-cache.outputs.cache-hit == 'true'
        run: |
          yarn compiler import-dependencies
          shx rm -rf compiler/_export

      - name: Build compiler
        run: |
          yarn compiler build

      - name: Build Binary
        run: |
          yarn cli build-pkg

      - name: Upload Binary Asset
        id: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.upload_url }}
          asset_path: ./pkg/grain
          asset_name: grain-${{ runner.os }}
          asset_content_type: application/octet-stream
