name: Build dependencies

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true

env:
  ESY__PREFIX: ${{ github.workspace }}/.esy/

jobs:
  build_dependencies:
    name: Create dependencies cache
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout project
        uses:  actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Esy dependency cache
        id: esy-cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.0.1
        with:
          path: compiler/_export
          key: ${{ runner.os }}-esy-${{ hashFiles('compiler/esy.lock/index.json') }}
          lookup-only: true

      # We only need to setup node & npm dependencies if we don't have an esy cache because
      # we won't run esy in that case and we can defer setting it up until building grain
      - name: Setup node.js
        if: steps.esy-cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ">=24.21 <25"
          check-latest: true
          cache: "npm"

      - name: Install npm dependencies
        if: steps.esy-cache.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Build esy dependencies
        if: steps.esy-cache.outputs.cache-hit != 'true'
        run: |
          npm run compiler prepare
          npm run compiler build-dependencies
          npm run compiler export-dependencies
